# @see https://github.com/rccyx/rlyx

version = "2.0.0"
default_bump = "patch"
bump_commit_message = "release v{{version}}"
post_bump_command = ""
bump_tag_message    = "release v{{version}}"
changelog_header    = "# Changelog"

[changelog]
enable = false
path   = "CHANGELOG.md"

[context]
enable = true
