option(ENABLE_LTO "Enable link-time optimization for optimized builds" OFF)

function(enable_hardening target)
  if(ENABLE_LTO)
    include(CheckIPOSupported)
    check_ipo_supported(RESULT ipo_supported OUTPUT ipo_error)
    if(ipo_supported)
      set_property(TARGET ${target} PROPERTY INTERPROCEDURAL_OPTIMIZATION TRUE)
    else()
      message(WARNING "LTO unavailable: ${ipo_error}")
    endif()
  endif()

  if(UNIX AND NOT APPLE)
    target_compile_options(${target} PRIVATE -fstack-protector-strong -D_FORTIFY_SOURCE=2)
    target_link_options(${target} PRIVATE -Wl,-z,relro -Wl,-z,now)
  endif()
endfunction()
