name: lint

on:
  workflow_call:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: base runner
        uses: ./.github/actions/base-runner

      - name: project install
        uses: ./.github/actions/project-install
        with:
          dev: "true"

      - name: lint
        run: just l
